# Generated by Django 4.2.3 on 2023-07-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(auto_now_add=True, verbose_name='Aniversário'),
        ),
    ]
