# Generated by Django 4.2.3 on 2023-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_imagem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='publicacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
