# Generated by Django 4.2.3 on 2023-07-27 13:49

from django.db import migrations, models
import main.gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_imagem_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='original',
            field=models.ImageField(blank=True, null=True, upload_to=main.gallery.models.upload_image_formater),
        ),
    ]
